import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import fs from 'node:fs';
import basePathPlugin from './vite.base-path-plugin';

// Plugin to ensure all asset paths in HTML include the base URL
function htmlAssetsPlugin() {
  return {
    name: 'html-assets',
    transformIndexHtml: {
      order: 'post',
      handler(html, { path: htmlPath = '' } = {}) {
        const isProduction = process.env.NODE_ENV === 'production';
        
        // Skip processing in development for non-HTML files
        if (!isProduction && !htmlPath.endsWith('.html')) {
          return html;
        }

        // Get the base URL from environment or use default
        const baseUrl = process.env.BASE_URL || '/Sahil-Portfolio/';
        const basePath = baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;

        // Function to process URLs in the HTML
        const processUrl = (url) => {
          // Skip if it's an external URL, data URL, or already has the base path
          if (url.startsWith('http') || 
              url.startsWith('//') || 
              url.startsWith('data:') ||
              url.startsWith(basePath) ||
              !url.startsWith('/')) {
            return url;
          }
          // Add base path if it's a root-relative path
          return `${basePath}${url.replace(/^\//, '')}`;
        };

        // Process src, href, and content attributes
        let result = html
          // Handle src and href attributes
          .replace(/(src|href)="([^"]*)"/g, (match, attr, url) => {
            return `${attr}="${processUrl(url)}"`;
          })
          // Handle CSS url() paths
          .replace(/url\(\s*['"]?([^'"#?)]+?)['"]?\s*\)/g, (match, p1) => {
            if (p1.startsWith('http') || p1.startsWith('data:')) {
              return match;
            }
            return `url("${processUrl(p1)}")`;
          })
          // Handle modulepreload
          .replace(/(<link[^>]+rel=["']modulepreload["'][^>]+href=["'])([^"']+)(["'])/g, 
            `$1${processUrl('$2')}$3`)
          // Handle script src
          .replace(/(<script[^>]+src=["'])([^"']+)(["'])/g, 
            `$1${processUrl('$2')}$3`)
          // Handle stylesheet links
          .replace(/(<link[^>]+rel=["']stylesheet["'][^>]+href=["'])([^"']+)(["'])/g, 
            `$1${processUrl('$2')}$3`);

        return result;
      }
    }
  };
}

// Get the directory name in ESM
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Load environment variables
const isGitHubPages = process.env.GITHUB_PAGES === 'true';
const isProduction = process.env.NODE_ENV === 'production';

// Set base URL based on environment
let base = '/';

// For GitHub Pages, always use the repository name as base path with trailing slash
if (isGitHubPages) {
  base = '/Sahil-Portfolio/';
} else if (isProduction) {
  base = '/';
}

// Ensure base URL is consistently formatted with a trailing slash
const baseUrl = base.endsWith('/') ? base : `${base}/`;

// Set environment variables for base URL
process.env.VITE_BASE_URL = baseUrl;
process.env.BASE_URL = baseUrl;

// Log the base URL for debugging
console.log(`Using base URL: "${baseUrl}"`);
console.log(`GitHub Pages: ${isGitHubPages}, Production: ${isProduction}`);

// Create a virtual module to expose the base URL to the client
const baseUrlModule = `
  // Auto-generated by Vite config
  export const baseUrl = '${baseUrl}';
  export default baseUrl;
`;

export default defineConfig({
  base: base,
  resolve: {
    extensions: ['.js', '.jsx', '.json', '.ts', '.tsx'],
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  server: {
    port: 5173,
    strictPort: true,
    open: true,
    host: 'localhost',
    hmr: {
      protocol: 'ws',
      host: 'localhost',
      port: 5173,
      overlay: false // Disable HMR overlay to prevent potential issues
    },
    fs: {
      // Allow serving files from one level up from the package root
      allow: ['..']
    },
    // Disable file system caching during development
    watch: {
      usePolling: true,
      interval: 100
    }
  },
  publicDir: 'public',
  build: {
    outDir: 'dist',
    assetsDir: 'assets',
    emptyOutDir: true,
    assetsInlineLimit: 4096, // 4kb - inline smaller assets as base64
    manifest: true,
    sourcemap: process.env.NODE_ENV === 'production' ? false : 'inline',
    minify: 'esbuild',
    cssMinify: 'esbuild',
    rollupOptions: {
      input: path.resolve(__dirname, 'index.html'),
      output: {
        experimentalMinChunkSize: 10000, // 10kb
        manualChunks(id) {
          if (id.includes('node_modules')) {
            if (id.includes('react') || id.includes('scheduler') || id.includes('object-assign')) {
              return 'vendor-react';
            }
            if (id.includes('@headlessui') || id.includes('@heroicons') || id.includes('@tailwindcss')) {
              return 'vendor-ui';
            }
            if (id.includes('framer-motion') || id.includes('popmotion')) {
              return 'vendor-animations';
            }
            if (id.includes('date-fns') || id.includes('lodash') || id.includes('axios')) {
              return 'vendor-utils';
            }
            return 'vendor-other';
          }
          if (id.includes('src/components/')) {
            const match = id.match(/src\/components\/([^/]+)/);
            if (match && match[1]) {
              return `component-${match[1].toLowerCase()}`;
            }
          }
        },
        assetFileNames: (assetInfo) => {
          const extType = assetInfo.name.split('.').at(1)?.toLowerCase();
          if (/png|jpe?g|svg|gif|tiff|bmp|ico|webp/i.test(extType)) {
            return 'assets/images/[name]-[hash][extname]';
          }
          if (/css/i.test(extType)) {
            return 'assets/css/[name]-[hash][extname]';
          }
          if (/js/i.test(extType)) {
            return 'assets/js/[name]-[hash][extname]';
          }
          return 'assets/misc/[name]-[hash][extname]';
        },
        chunkFileNames: (chunkInfo) => {
          if (chunkInfo.name.startsWith('vendor-')) {
            return 'assets/js/vendor/[name]-[hash].js';
          }
          if (chunkInfo.name.startsWith('component-')) {
            return 'assets/js/components/[name]-[hash].js';
          }
          return 'assets/js/[name]-[hash].js';
        },
        entryFileNames: 'assets/js/[name]-[hash].js',
      }
    },
    assetsInlineLimit: 4096, // 4kb - inline smaller assets as base64
    manifest: true, // Generate manifest.json
    assetsInclude: ['**/*.avif', '**/*.webp', '**/*.png', '**/*.jpg', '**/*.jpeg', '**/*.gif', '**/*.svg'],
  },
  preview: {
    port: 3000,
    open: true
  },
  plugins: [
    {
      name: 'virtual-base-url',
      resolveId(id) {
        if (id === 'virtual:base-url') {
          return '\0virtual:base-url';
        }
      },
      load(id) {
        if (id === '\0virtual:base-url') {
          return baseUrlModule;
        }
      },
    },
    react({
      jsxImportSource: 'react',
      jsxRuntime: 'automatic',
      babel: {
        plugins: [],
      },
    }),
    basePathPlugin(),
    htmlAssetsPlugin(),
    {
      name: 'copy-service-worker',
      apply: 'build',
      generateBundle() {
        this.emitFile({
          type: 'asset',
          fileName: 'service-worker.js',
          source: fs.readFileSync(path.resolve(__dirname, 'public/service-worker.js'), 'utf-8')
        });
      }
    },
  ],
  css: {
    modules: {
      localsConvention: 'camelCaseOnly',
    },
    devSourcemap: true,
    preprocessorOptions: {
      scss: { 
        additionalData: `@import "src/styles/variables.scss";`,
      },
    },
  },
  
  optimizeDeps: {
    include: [
      'react', 
      'react-dom', 
      'react-dom/client', 
      'react-router-dom',
      'framer-motion', 
      'react-helmet', 
      'react-helmet-async',
      'react-icons/fa', 
      'react-icons/fi', 
      'react-icons/bs', 
      'react-icons/si',
      'react-icons/io5', 
      'react-icons/md', 
      '@sentry/react', 
      'plausible',
      'date-fns', 
      'date-fns-tz',
    ],
    exclude: ['js-big-decimal'],
    force: true,
    esbuildOptions: {
      loader: { '.js': 'jsx' },
      target: 'es2020',
    },
  },
});