// This file is auto-generated by Vite
// It provides the base URL for the application

// In development, this will be '/'
// On GitHub Pages, this will be '/Sahil-Portfolio/'
const baseUrl = import.meta.env.BASE_URL || '/';

export default baseUrl.endsWith('/') ? baseUrl : `${baseUrl}/`;
