name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install dependencies
      run: |
        echo "Node.js version: $(node -v)"
        echo "npm version: $(npm -v)"
        npm ci --no-audit --legacy-peer-deps
    
    - name: Check dependency tree
      run: npm ls ajv postcss-selector-parser rollup picomatch
    
    - name: Build
      run: npm run build --if-present
    
    - name: Test
      run: npm test --if-present
